name: actions

on: 
  push:
    branches:
      - master

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer dependecies
        run: composer install
      - run: ./vendor/bin/grumphp run